### ISSUE TITLE
Error getBaseRequest() java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by gonafr** [ahus1/keycloak-dropwizard-integration#16]
Hi,

I'm getting the following error when try to access a resource. 
Can someone help?

Thanks in advance.

```
WARN  [2017-07-26 15:50:04,626] org.eclipse.jetty.server.HttpChannel: /greetings/oscar
! java.lang.NoSuchMethodError: org.eclipse.jetty.server.Request.getBaseRequest(Ljavax/servlet/ServletRequest;)Lorg/eclipse/jetty/server/Request;
! at org.keycloak.adapters.jetty.KeycloakJettyAuthenticator.resolveRequest(KeycloakJettyAuthenticator.java:46) ~[keycloak-jetty94-adapter-3.0.0.Final.jar:3.0.0.Final]
! at org.keycloak.adapters.jetty.core.AbstractKeycloakJettyAuthenticator.validateRequest(AbstractKeycloakJettyAuthenticator.java:285) ~[keycloak-jetty-core-3.0.0.Final.jar:3.0.0.Final]
! at de.ahus1.keycloak.dropwizard.KeycloakDropwizardAuthenticator.validateRequest(KeycloakDropwizardAuthenticator.java:42) ~[keycloak-dropwizard-1.0.0.jar:na]
! at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:512) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[oauth2-dropwizard-1.0.jar:na]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) ~[oauth2-dropwizard-1.0.jar:na]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.Server.handle(Server.java:499) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) ~[oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [oauth2-dropwizard-1.0.jar:na]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [oauth2-dropwizard-1.0.jar:na]
! at java.lang.Thread.run(Unknown Source) [na:1.8.0_131]
```

**Comment by ahus1** [comment]
It seems to me that you try to mix keycloak-dropwizard-1.0.0.jar with dropwizard-1.0 (if I read the JAR file names in your stack trace correctly).

This is not supported.

Please have a look at the docs in the README in the root of the repository to pick matching versions:

* Version 0.9.x is tested with Keycloak 2.x.x/3.x.x and Dropwizard 1.0.x
* Version 1.0.x is tested with Keycloak 3.x.x and Dropwizard 1.1.x

If this solves your problem, please close this ticket. If not, please post the versions you are using (dropwizard, keycloak server, keycloak client). 

Thanks!

**Comment by gonafr** [comment]
I think I'm using dropwizard 1.1.2, please check the jars i use.
Thank you for your help.

`[INFO] Including io.dropwizard:dropwizard-core:jar:1.1.2 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-util:jar:1.1.2 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0 in the shaded jar.
[INFO] Including com.google.guava:guava:jar:21.0 in the shaded jar.
[INFO] Including com.google.code.findbugs:jsr305:jar:3.0.1 in the shaded jar.
[INFO] Including joda-time:joda-time:jar:2.9.7 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-jackson:jar:1.1.2 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-core:jar:2.8.9 in the shaded jar.
[INFO] Including com.fasterxml.jackson.core:jackson-databind:jar:2.8.9 in the shaded jar.
[INFO] Including com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.8.9 in the shaded jar.
[INFO] Including com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.8.9 in the shaded jar.
[INFO] Including com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.8.9 in the shaded jar.
[INFO] Including com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.8.9 in the shaded jar.
[INFO] Including com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.8.9 in the shaded jar.
[INFO] Including com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.8.9 in the shaded jar.
[INFO] Including org.slf4j:slf4j-api:jar:1.7.24 in the shaded jar.
[INFO] Including ch.qos.logback:logback-classic:jar:1.2.1 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-validation:jar:1.1.2 in the shaded jar.
[INFO] Including org.hibernate:hibernate-validator:jar:5.3.4.Final in the shaded jar.
[INFO] Including javax.validation:validation-api:jar:1.1.0.Final in the shaded jar.
[INFO] Including com.fasterxml:classmate:jar:1.3.3 in the shaded jar.
[INFO] Including org.glassfish:javax.el:jar:3.0.0 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-configuration:jar:1.1.2 in the shaded jar.
[INFO] Including com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.8.9 in the shaded jar.
[INFO] Including org.yaml:snakeyaml:jar:1.17 in the shaded jar.
[INFO] Including org.apache.commons:commons-lang3:jar:3.5 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-logging:jar:1.1.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-logback:jar:3.2.2 in the shaded jar.
[INFO] Including org.slf4j:jul-to-slf4j:jar:1.7.24 in the shaded jar.
[INFO] Including ch.qos.logback:logback-core:jar:1.2.1 in the shaded jar.
[INFO] Including org.slf4j:log4j-over-slf4j:jar:1.7.24 in the shaded jar.
[INFO] Including org.slf4j:jcl-over-slf4j:jar:1.7.24 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-util:jar:9.4.2.v20170220 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-metrics:jar:1.1.2 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-jersey:jar:1.1.2 in the shaded jar.
[INFO] Including org.glassfish.jersey.core:jersey-server:jar:2.25.1 in the shaded jar.
[INFO] Including org.glassfish.jersey.core:jersey-common:jar:2.25.1 in the shaded jar.
[INFO] Including org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.25.1 in the shaded jar.
[INFO] Including org.glassfish.hk2:osgi-resource-locator:jar:1.0.1 in the shaded jar.
[INFO] Including org.glassfish.jersey.core:jersey-client:jar:2.25.1 in the shaded jar.
[INFO] Including javax.ws.rs:javax.ws.rs-api:jar:2.0.1 in the shaded jar.
[INFO] Including org.glassfish.jersey.media:jersey-media-jaxb:jar:2.25.1 in the shaded jar.
[INFO] Including javax.annotation:javax.annotation-api:jar:1.2 in the shaded jar.
[INFO] Including org.glassfish.hk2:hk2-api:jar:2.5.0-b32 in the shaded jar.
[INFO] Including org.glassfish.hk2:hk2-utils:jar:2.5.0-b32 in the shaded jar.
[INFO] Including org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0-b32 in the shaded jar.
[INFO] Including org.glassfish.hk2.external:javax.inject:jar:2.5.0-b32 in the shaded jar.
[INFO] Including org.glassfish.hk2:hk2-locator:jar:2.5.0-b32 in the shaded jar.
[INFO] Including org.javassist:javassist:jar:3.21.0-GA in the shaded jar.
[INFO] Including org.glassfish.jersey.ext:jersey-metainf-services:jar:2.25.1 in the shaded jar.
[INFO] Including org.glassfish.jersey.ext:jersey-bean-validation:jar:2.25.1 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-jersey2:jar:3.2.2 in the shaded jar.
[INFO] Including com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.8.9 in the shaded jar.
[INFO] Including com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.8.9 in the shaded jar.
[INFO] Including com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.8.9 in the shaded jar.
[INFO] Including org.glassfish.jersey.containers:jersey-container-servlet:jar:2.25.1 in the shaded jar.
[INFO] Including org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.25.1 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-server:jar:9.4.2.v20170220 in the shaded jar.
[INFO] Including javax.servlet:javax.servlet-api:jar:3.1.0 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-io:jar:9.4.2.v20170220 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-webapp:jar:9.4.2.v20170220 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-xml:jar:9.4.2.v20170220 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-continuation:jar:9.4.2.v20170220 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-servlets:jar:1.1.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-annotation:jar:3.2.2 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-jetty:jar:1.1.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-jetty9:jar:3.2.2 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-servlet:jar:9.4.2.v20170220 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-security:jar:9.4.2.v20170220 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-servlets:jar:9.4.2.v20170220 in the shaded jar.
[INFO] Including org.eclipse.jetty:jetty-http:jar:9.4.2.v20170220 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-lifecycle:jar:1.1.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-core:jar:3.2.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-jvm:jar:3.2.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-servlets:jar:3.2.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-json:jar:3.2.2 in the shaded jar.
[INFO] Including com.papertrail:profiler:jar:1.0.2 in the shaded jar.
[INFO] Including io.dropwizard.metrics:metrics-healthchecks:jar:3.2.2 in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-request-logging:jar:1.1.2 in the shaded jar.
[INFO] Including ch.qos.logback:logback-access:jar:1.2.1 in the shaded jar.
[INFO] Including net.sourceforge.argparse4j:argparse4j:jar:0.7.0 in the shaded jar.
[INFO] Including org.eclipse.jetty.toolchain.setuid:jetty-setuid-java:jar:1.0.3 in the shaded jar.
[INFO] Including de.ahus1.keycloak.dropwizard:keycloak-dropwizard:jar:1.0.0 in the shaded jar.
[INFO] Including org.keycloak:keycloak-jetty94-adapter:jar:3.0.0.Final in the shaded jar.
[INFO] Including org.jboss.logging:jboss-logging:jar:3.3.0.Final in the shaded jar.
[INFO] Including org.keycloak:keycloak-core:jar:3.0.0.Final in the shaded jar.
[INFO] Including org.keycloak:keycloak-common:jar:3.0.0.Final in the shaded jar.
[INFO] Including org.bouncycastle:bcpkix-jdk15on:jar:1.52 in the shaded jar.
[INFO] Including org.keycloak:keycloak-adapter-core:jar:3.0.0.Final in the shaded jar.
[INFO] Including org.keycloak:keycloak-jetty-core:jar:3.0.0.Final in the shaded jar.
[INFO] Including org.keycloak:keycloak-jetty-adapter-spi:jar:3.0.0.Final in the shaded jar.
[INFO] Including org.bouncycastle:bcprov-jdk15on:jar:1.52 in the shaded jar.
[INFO] Including org.keycloak:keycloak-jaxrs-oauth-client:jar:3.0.0.Final in the shaded jar.
[INFO] Including org.keycloak:keycloak-adapter-spi:jar:3.0.0.Final in the shaded jar.
[INFO] Including io.dropwizard:dropwizard-auth:jar:1.1.2 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpclient:jar:4.5.3 in the shaded jar.
[INFO] Including org.apache.httpcomponents:httpcore:jar:4.4.6 in the shaded jar.
[INFO] Including commons-codec:commons-codec:jar:1.9 in the shaded jar.`

**Comment by ahus1** [comment]
The versions you use seem to be ok. I tried an update of the keycloak-dropwizard-jaxrs-example and keycloak-dropwizard-bearermodule in this project to dropwizard 1.1.2 and I didn't see the described situation. Maybe you can use one of these projects as a starting point and see what piece differs.

**Comment by gonafr** [comment]
When I try to build the example (keycloak-dropwizard-jaxrs-example) I got an error.
Can you help?

`[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building keycloak-dropwizard-jaxrs-example 1.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for de.ahus1.keycloak.dropwizard:domain:jar:1.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for de.ahus1.keycloak.dropwizard:keycloak-dropwizard:jar:1.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.737 s
[INFO] Finished at: 2017-08-01T16:01:54+01:00
[INFO] Final Memory: 14M/221M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project keycloak-dropwizard-jaxrs-example: Could not resolve dependencies for project de.ahus1.keycloak.dropwizard:keycloak-dropwizard-jaxrs-example:jar:1.0.1-SNAPSHOT: The following artifacts could not be resolved: de.ahus1.keycloak.dropwizard:domain:jar:1.0.1-SNAPSHOT, de.ahus1.keycloak.dropwizard:keycloak-dropwizard:jar:1.0.1-SNAPSHOT: Failure to find de.ahus1.keycloak.dropwizard:domain:jar:1.0.1-SNAPSHOT in https://repository.jboss.org/nexus/content/repositories/releases/ was cached in the local repository, resolution will not be reattempted until the update interval of jboss-releases has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

**Comment by ahus1** [comment]
When pasting pre-formatted console output, please use four backticks to keep the pre-formatted layout. I updated your previous postings. 

The keycloak-dropwizard-jaxrs-example is a maven module that depends on two other maven modules. To build it directly use `mvn -am -pl keycloak-dropwizard-jaxrs-example compile` in the root folder of the project. This will automatically build the depending modules. 

To derive your own project, copy the folder to a separate directory, remote the reference to the parent project, and replace the SNAPSHOT versions with a matching released version from maven central. This should get you going, and you can then use the usual maven commands.

I have to admit that this setup is not as easy as it can be to start with. Maybe you can get into tough with a friend or colleague that is experienced with Maven to help out here.

**Comment by gonafr** [comment]
The problem was a wrong reference on the build path.

Thank you for your support.
I got everything working now.

**Comment by ahus1** [comment]
Good to hear that you found it. I'm closing this bug. 

If you want, to can leave comments for other how you found the wrong reference and/or how to prevent it.
