### ISSUE TITLE
Why do you choose Dropwizard

### ISSUE THREAD

**Issue by HelloTo4x** [ahus1/keycloak-dropwizard-integration#189]
Hi, i am reading your repository and i am interested in this, but i have a question, you use Dropwizard to achieve high concurrency in Java, is it correct ? Why don't u choose others like Netty or Reactive Programming ? Can you tell me the purpose of Dropwizard in your project, and the pros and cons of Dropwizard, thank u so much

**Comment by ahus1** [comment]
This is not a repository to discuss Dropwizard in general.
