### ISSUE TITLE
Package a first release

### ISSUE THREAD

**Issue by ahus1** [ahus1/keycloak-dropwizard-integration#2]
This task aims to prepare a first release.

**Comment by ahus1** [comment]
Hello Nic (aka @grange74),

a first release 0.2.0 is now available on Bintray. 

Please give it a try and let me know if I missed anything. 

Best regards,
Alexander.

    <repositories>
      <repository>
        <id>bintray-ahus1</id>
        <name>Maven Repository of Alexander Schwartz</name>
        <url>https://dl.bintray.com/ahus1/maven/</url>
      </repository>    
    </repositories>
    <dependencies>
      <dependency>
        <groupId>de.ahus1.keycloak.dropwizard</groupId>
        <artifactId>keycloak-dropwizard</artifactId>
        <version>0.2.0</version>
      </dependency>
    </dependencies>

**Comment by grange74** [comment]
Just changed my example to use the official release and it works great :+1:

**Comment by ahus1** [comment]
Twitter about new release already completed by Nic: https://twitter.com/ngrange/status/652758892724621312

**Comment by grange74** [comment]
I hope your ok with that tweet.. it wasn't meant to replace an official announcement.. i was just excited about the release and wanted to help spread the word..

I also noticed the module has now been published on http://modules.dropwizard.io/thirdparty/

**Comment by ahus1** [comment]
No offense meant, no offense taken!

The module update took some time. The Dropwizards module directory apparently has a master and a ghpages branch. This adds another level of indirection (and time).

BTW: I am in the process of adding this project to maven central. https://issues.sonatype.org/plugins/servlet/mobile#issue/OSSRH-18188

I wonder how that works out. It's the first time for me...

**Comment by ahus1** [comment]
... done, with a proof: http://central.maven.org/maven2/de/ahus1/keycloak/dropwizard/keycloak-dropwizard/0.2.1/

The release 0.2.1 adds only some mandatory elements to `pom.xml`s. No other change.

I'm happy!

**Comment by grange74** [comment]
Great work. 

A few days ago, I recommended this module to one of my work colleagues and since he has included it in a Dropwizard project that his team is working on. The feedback was very good, it worked seamlessly and was super simple to integrate. :+1:
