### ISSUE TITLE
Extend/Override KeycloakAuthFilter?

### ISSUE THREAD

**Issue by steve-thousand** [ahus1/keycloak-dropwizard-integration#26]
I have a desire to override the `createRequestAuthenticator` method in the `KeycloakAuthFilter` class, so that I can provide a slightly modified version of the `JettyRequestAuthenticator`, however the way that the class is written makes this very hard to do (private constructor, private builder). I still haven't found a way to do this, do you have a recommended course of action?

**Comment by steve-thousand** [comment]
Update on this: I was looking at the `KeycloakAuthFilter` but it turns out my requests were being handled by the `KeycloakDropwizardAuthenticator` which caused some confusion. I was able to do what I needed to do by overriding methods in the authenticator, but the presence of the two classes and their request handlers was confusing. Is there a need for both?

**Comment by ahus1** [comment]
Glad to hear you made it work. 

If I recall it correctly the two classes were necessary to handle different situation with authenticated/un-authenticated requests.
