### ISSUE TITLE
Support DropWizard 4

### ISSUE THREAD

**Issue by erasmas** [ahus1/keycloak-dropwizard-integration#287]
Hello and first of all thank you for this library.

We've been using it in production for the last couple of years with DropWizard 2.

I am looking into upgrading our services to DW4 which has a newer version of Jetty and relies on Jakarta instead of JEE. I spent some time trying to prepare a PR to update `keycloak-dropwizard-integration` to `dropwizard:4.0.1` but I got stuck updating `KeycloakDropwizardAuthenticator` because `org.keycloak.adapters.jetty.core.AbstractKeycloakJettyAuthenticator` still uses `javax` package. 

I'm happy to finish the work and submit a PR but I'd appreciate some high level guidance on what is the path forward to upgrade to DropWizard 4. Thank you!

**Comment by ahus1** [comment]
Hi @erasmas - from what I read at the upstream Keycloak project, they discourage to use their client adapters; they deprecated them a while ago. 

So I'd suggest to adopt their sources and transform them to Jakarta EE as needed. I prepared a Dropwizard-4 branch here: https://github.com/ahus1/keycloak-dropwizard-integration/tree/dropwizard-4

While it compiles, the tests don't pass yet. Feel free to take this as an inspiration, or create a PR for that branch. I might continue this depending on the time I have at my hands. 

Once the tests are green, we might think of moving the classes to a non-Keycloak package to avoid confusion.

**Comment by ahus1** [comment]
There is now a pull-request #338 which upgrades to Dropwizard 4. I'd be happy to get feedback on this before I merge it.

**Comment by erasmas** [comment]
Awesome! I'll be happy to give it a try next week! Appreciate you working on it! 🙏

**Comment by erasmas** [comment]
Sorry it took me so long again to reply, I finally got to try this version but apparently can't download it from the repository you mentioned.

```build.gradle
buildscript {
    repositories {
...
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots'
            name 'snapshots-repo'
            mavenContent {
                snapshotsOnly()
            }
        }
    }
...
```

```
> gradlew build
...
* What went wrong:
A problem occurred configuring root project 'draftwise'.
> Could not compute lock state from configuration 'unifiedClasspath' due to unresolved dependencies:
   * de.ahus1.keycloak.dropwizard:keycloak-dropwizard:3.0.0-SNAPSHOT (requested: 'de.ahus1.keycloak.dropwizard:keycloak-dropwizard' because: requested)
        Failures:
           - Could not resolve de.ahus1.keycloak.dropwizard:keycloak-dropwizard:3.0.0-SNAPSHOT.
           - Could not resolve de.ahus1.keycloak.dropwizard:keycloak-dropwizard:3.0.0-SNAPSHOT.
           - Unable to load Maven meta-data from https://d1osg35nybn3tt.cloudfront.net/de/ahus1/keycloak/dropwizard/keycloak-dropwizard/3.0.0-SNAPSHOT/maven-metadata.xml.
           - Could not GET 'https://d1osg35nybn3tt.cloudfront.net/de/ahus1/keycloak/dropwizard/keycloak-dropwizard/3.0.0-SNAPSHOT/maven-metadata.xml'. Received status code 403 from server: Forbidden
```

**Comment by ahus1** [comment]
Thanks for trying this out. I opened the URL https://oss.sonatype.org/content/repositories/snapshots/de/ahus1/keycloak/dropwizard/keycloak-dropwizard/3.0.0-SNAPSHOT/ and this shows me that all expected files are there, including `maven-metadata.xml`

Hm, could you please check/debug your Gradle configuration? I have to admit I'm not a Gradle pro, I usually use Maven.

It is strange to me that cloudfront appears in the URL, it doesn't do that when I access it via my browser.

**Comment by erasmas** [comment]
> Thanks for trying this out. I opened the URL https://oss.sonatype.org/content/repositories/snapshots/de/ahus1/keycloak/dropwizard/keycloak-dropwizard/3.0.0-SNAPSHOT/ and this shows me that all expected files are there, including `maven-metadata.xml`
> 
> Hm, could you please check/debug your Gradle configuration? I have to admit I'm not a Gradle pro, I usually use Maven.
> 
> It is strange to me that cloudfront appears in the URL, it doesn't do that when I access it via my browser.

Hi Ahus! I apologize; that was my fault, as I placed the repository configuration in the wrong location. I'm now able to pull the dependency, and I've verified that the login flow works with Keycloak. I haven't conducted any extensive testing beyond verifying that SSO login functions correctly. I'm not sure if this gives you enough information and assurance to merge this PR, but it looks good to me, and I'm very much looking forward to the `3.0.0-release` ! Thank you for your work!

**Comment by ahus1** [comment]
Thank you for testing, it is now merged. I'll plan to prepare a release next week.

**Comment by ahus1** [comment]
Version 3.0.0 of this project has been released and should be available on Maven central shortly.

**Comment by erasmas** [comment]
Thank you! 🙏
