### ISSUE TITLE
KeycloakBundle adding extra Authentication to AssetBundle

### ISSUE THREAD

**Issue by nate9** [ahus1/keycloak-dropwizard-integration#3]
Hello,

I was wondering if you could help with a specific problem I am facing?

My dropwizard setup is as follows:
* Dropwizard using the KeycloakBundle
* Api in dropwizard at an api endpoint, e.g '/api'
* An AssetBundle also registered serving HTML5 assets, at a ui endpoint e.g '/ui'

The HTML5 asset uses the keycloak javascript adapter, which redirects the page to the keycloak login page, which, after login, sends the browser back to the html page. However, it adds an openid/oauth ?code= param, which Dropwizard will respond to with a 401 Unauthorised.

I was wondering if there is a way for the KeycloakBundle to ignore authentication given a path? E.G. Ignore trying to authenticate anything that is under '/ui/*'. For our intents Dropwizard is simply serving a REST API and an HTML5 Application on the same host. While it is possible to separate both of them I was wondering if there was an easy way to simply ignore authentication for the HTML5 component.

Cheers,

**Comment by ahus1** [comment]
What you try to do makes sense, but it seems that the current implementation needs to adopt to it.

Currently KeycloakDropwizardAuthenticator is quite eager to capture everything that has a code query parameter.

I wonder if all asset bundles should be excluded (that would effectively disable authentication for them). Or would you be OK to pass a list of excluded URL params to the module?

Please suggest what you would consider the right default handling... I hope to something ready Dover the next days.

**Comment by ahus1** [comment]
BTW, is your API bearer token only? I might use this information to do the right thing in KeycloakDrowizardAuthenticator automatically...

**Comment by nate9** [comment]
Currently our API is 'confidential'.

I think because AssetBundle is a dropwizard plugin of sorts, you should build it orthogonally and not need to worry about trying to determine whether or not an AssetServlet should be authenticated. Simply having a list of excluded URL params would be fine, I can pass this in through the config to both the AssetBundle and the KeyCloak bundle.

Cheers

**Comment by ahus1** [comment]
I assume that you want only your JavaScript client to do the OAuth redirect. I also assume that your API will always expect a Bearer token, and should never issue an OAuth redirect on itself.

The only change for your application would be adding the following line to your application's configuration: 

    keycloakConfiguration:
      bearerOnly: true

I pushed a code change referencing this ticket number to change the adapter. I also included an example application that should cover your use case. Follow this link to the example application: https://github.com/ahus1/keycloak-dropwizard-integration/tree/master/keycloak-dropwizard-bearermodule

An snapshot version 0.3.1-SNAPSHOT is available here from the snapshot repository: https://oss.sonatype.org/content/repositories/snapshots/

Please let me know if this works for you. If it works for you I'll release the change. If not I'll have to consider an exclusion list.

**Comment by nate9** [comment]
Sure, I'll give it a try.

Thanks.

**Comment by ahus1** [comment]
I've released the changes as version 0.4.0. I'll close ticket once I received feedback from you.

**Comment by nate9** [comment]
Hey ahus1,

We've changed our REST API to use bearer only and followed your examples to configure the javascript client. Seems to work fine for our use cases. I think we can expose a rest api for the keycloak.js 's json configuration object, so we won't have to hardcode the keycloak server url, which should be fine.

Thanks for the help!

**Comment by ahus1** [comment]
"can expose a rest api for ... keycloak.js" - sounds cool!

Feel free to "pimp" the example javascript example application with a pull request.

**Comment by nate9** [comment]
Hey ahus1,

We have found that for requests which do not have a Authorization/Bearer header, instead of returning a 403 Forbidden, it returns a 500 internal server error. Logs indicate that it seems to trying to authenticate through the session/cookies? It then throws an error because No session manager is provided by Dropwizard.

If an invalid bearer token is provided, it will throw 403, but if no bearer token is there, it will throw a 500 error. I'm not sure if this is the expected behaviour. Most of this logic seems to be handled by org.keycloak.adapters.RequestAuthenticator.

**Comment by ahus1** [comment]
I haved moved this to ticket #4
