### ISSUE TITLE
JaxrsBearerTokenFilterImpl deprecated

### ISSUE THREAD

**Issue by emreozen** [ahus1/keycloak-dropwizard-integration#40]
Thanks for this great library! 

[JaxrsBearerTokenFilterImpl](https://github.com/keycloak/keycloak/blob/master/adapters/oidc/jaxrs-oauth-client/src/main/java/org/keycloak/jaxrs/JaxrsBearerTokenFilterImpl.java) used in `keycloak-dropwizard-bearer` and `keycloak-dropwizard-bearermodule` is being deprecated - do you know any alternatives to it?

**Comment by ahus1** [comment]
This class has been deprecated for a while. I don't know about alternatives. 

The strategy for `keycloak-dropwizard-bearermodule`: I'll internalize the class into the library once it is no longer available in the main keycloak distribution. 

I hope this answers your question. Please close this ticket if it does.

**Comment by emreozen** [comment]
Sounds good, thank you!
