### ISSUE TITLE
Failing to register node to Keycloak

### ISSUE THREAD

**Issue by emreozen** [ahus1/keycloak-dropwizard-integration#41]
Getting the following error similar to: https://github.com/ahus1/keycloak-dropwizard-integration/issues/31
```
ERROR NodesRegistrationManagement failed to register node to keycloak
ERROR NodesRegistrationManagement status from server: 200
ERROR NodesRegistrationManagement    {"error":"unknown_error"}
```
I am on versions: 
de.ahus1.keycloak.dropwizard:keycloak-dropwizard = 1.1.3
org.keycloak:* = 11.0.2

Did I get the versions conflicted?

**Comment by ahus1** [comment]
Hi Emre, 

in the issue you mention above there is a the reason for the error (as I understand it): 

> the errors were because I didn't have service accounts enabled for my client.

That's a client-specific setting in the Keycloak server. Please give it a try.

**Comment by emreozen** [comment]
Thank you - it was an issue with the reverse proxy of my server
