### ISSUE TITLE
Support Keycloak 2.0

### ISSUE THREAD

**Issue by anthonyraymond** [ahus1/keycloak-dropwizard-integration#8]
Hi,
i wonder if you are planning to support [keycloak 2.0](http://www.keycloak.org/) in a near future?
I don't know if the Java API has changed so i don't know how complicated it will be.

Anthony.

**Comment by ahus1** [comment]
Hello Anthony,

Welcome back. I was thinking to support both Dropwizard 1.0 and Keycloak 2.0 in the next minor release. The update of Keycloak worked quite well, but for Dropwizard 1.0 I need Keycloak to support Jetty 9.3. I submitted a PR to Keycloak for this (see other ticket). But I assume it will take at least until Keycloak 2.1 for it to be part of a release.

So I should probably issue a release without Dropwizard 1.0 support.

Do you plan to use any of the new Keycloak 2.0 features in your project?

Regards, Alexander

**Comment by anthonyraymond** [comment]
Hi,
It make sense to update both Dropwizard and keycloak at the same time. Glad to hear you are ready to go on it.

I'm planning to, but no 2.0 features are game changers so far, we're hopping to see "full-export" from admin console in a near future, but without this feature, we don't plan to update to Keycloak 2.

So if i am the only that is "interessted" in Keycloak 2 support for Dropwizard 0.9, it might not worth it.

Anthony.

**Comment by ahus1** [comment]
Keycloak 2.0 is now supported in Release 0.8.0

**Comment by anthonyraymond** [comment]
Thanks fot that ;)
