### ISSUE TITLE
Support Keycloak 2.5.4

### ISSUE THREAD

**Issue by reneploetz** [ahus1/keycloak-dropwizard-integration#9]
Keycloak 2.5.4 broke the Adapter SPI in HttpFacade in https://github.com/keycloak/keycloak/commit/13e92cdb35d84cb2663a36bf4775134a05f1a429

I can provide a pull request if you want but I'm unsure if what your policy on versioning / API stability is (the change might be introduced without breaking the 2.1.0 API as you can just add the method, but that might not be a good idea development-wise).

**Comment by ahus1** [comment]
Hello René, thanks for reporting this. 

I see your point regarding versioning and API stability. 

Please go ahead an add the method, but comment out the `@Override` annotation for the new method for now to keep it working for different Keycloak versions. Please also add a TODO to re-activate the `@Override` once the library bumps to the next version. 

I'll try to release a 0.9.x and 0.8.x version shortly after the PR.

**Comment by ahus1** [comment]
Thanks for providing the fix. This is now available as 0.9.1 on maven central. I also update the dropwizard and keycloak dependencies on the most recent patch levels.

**Comment by reneploetz** [comment]
Thanks! 

But there might be a misunderstanding, as I thought about not increasing the Keycloak dependencies in the POM and just add the method. 
Yes, older Keycloak dependencies can be used and will work flawlessly (using Maven excludes etc), but if you update to the latest version, you do not need to remove the @Override annotation as it has RetentionPolicy.SOURCE anyway (it's only checked at compile time). But anyway, it works :)

**Comment by ahus1** [comment]
Rene, I wanted to see your change to work with the old and the new version of Keycloak. And your change worked very well with both versions. Just to make sure that nothing breaks.

But you are right - now that I updated the dependencies I can activate the Override.

**Comment by reneploetz** [comment]
I understand. Thanks again for testing and getting this in so fast :)
