### ISSUE TITLE
Returning a 200 response when a protected endpoint is hit without a Token

### ISSUE THREAD

**Issue by emreozen** [ahus1/keycloak-dropwizard-integration#94]
Thanks for the great library!

We are hitting the following issue, where it returns a 200 response when a protected endpoint is hit without a Token
DW version: 1.3.23
keycloak-dw version: 1.1.3
Running on: OpenJdk 11

Using bearer-only

When we hit a protected endpoint without sending a Bearer Token we get a 200 response instead of 401. 
It seems like, we end up here: https://github.com/ahus1/keycloak-dropwizard-integration/blob/master/keycloak-dropwizard/src/main/java/de/ahus1/keycloak/dropwizard/KeycloakDropwizardAuthenticator.java#L39-L44

return a null `authentication` object which results a 200 response code. Would it make sense to change it to 401?

**Comment by ahus1** [comment]
Hi Emre, long time no see!

I'll need to look into the code to figure out what the current behavior is. [Looking at the tests](https://github.com/ahus1/keycloak-dropwizard-integration/blob/master/keycloak-dropwizard-bearermodule/src/test/java/de/ahus1/lottery/adapter/dropwizard/LotteryApplicationTestWithBearerOnly.java#L52-L58) it should work fine.

Reading your questions I got some more questions: 

* How did you protect your endpoint? Did you use `@RolesAllowed` or did you implement a different mechanism?
* Is the 200 OK returned after your endpoint implementation is called?

**Comment by ahus1** [comment]
(I just noticed that this test was added for version 1.2.0 ... but the code we're looking at here didn't change between 1.1.3 and 1.2.0 AFAIK)

**Comment by emreozen** [comment]
Thanks! I hope you are doing well. I just updated to 1.2.0, but no changes. 

- Regarding `@RolesAllowed` We are not using any roles, basically allowing everyone with a valid token through. 
- without a bear token, it does not go into our endpoint implementation, it gets through  `KeycloakDropwizardAuthenticator` and then `SecurityHandler` and returns 200

I am getting a 401 when I send an empty bearer token as expected. 
sending a `-H 'authorization: Bearer '` via curl vs. not sending anything at all

**Comment by ahus1** [comment]
The behavior I would expect for no token and setting no restriction in the resource would be to make the call pass to the resource. This would be the anonymous access to a resource. 

I'll have to investigate further. It might take some days for me to find the time.

**Comment by ahus1** [comment]
I had a look and wasn't able to reproduce the behavior "no token - not called endpoint - return code 200". 

What I did:
* started the example in keycloak-dropwizard-bearermodule using the example 

```
mvn test -pl keycloak-dropwizard-bearermodule -am -Pkeycloak-dropwizard-bearermodule
```

* calling and endpoint that requires authentication and authorization: 

```
$ curl 'http://localhost:9090/whoami' -v
> GET /whoami HTTP/1.1
> Host: localhost:9090
< HTTP/1.1 401 Unauthorized
< WWW-Authenticate: Bearer realm="test"
```

* calling and endpoint that doesn't require authentication and authorization: 

```
$ curl 'http://localhost:9090/logout' -v
> GET /logout HTTP/1.1
< HTTP/1.1 200 OK
``` 

I then started to remote elements from the "whoami" endpoint. Once I removed the annotation `@RolesAllowed("user")` AND the method parameter `@Auth User user`, the return code changed to 200. The method was called and set the dummy name to the bean that I added. Dropwizard 0.8 there was a `required` attribute for the `@Auth` annotation where you could have optional authentication, but that went away in Drowizard 0.9 (see: https://github.com/dropwizard/dropwizard/issues/1320).

This boils as far as I can see down to:
* no token and one of `@Role`/`@Auth` present, a 401 code is returned
* no token and and neither `@Role`/`@Auth` present, the method is called and 200 code is returned. 

The workaround for optional authentication in endpoints is shown in the logout code: 

```
@GET
@Path("/logout")
public LogoutView logout(@Context SecurityContext context) throws ServletException { 
    if (context.getUserPrincipal() != null) {
        request.logout();
    }
    return new LogoutView();
}
``` 

While the behavior of `@Auth` to enforce an authentication was a little bit surprising to me, as a whole it behaves as expected to me. Having a way to mark different URLs/resources to require and not to require authentication is essential to the projects I've seen. 

To investigate further, I ask you to provide a pull request or branch with a test case for this project, or a small stand-alone project.

**Comment by emreozen** [comment]
Hi @ahus1, 

Thank you very much for looking into this for us. I resolved it by making sure both @Auth and @Role are present. I don't think we need to investigate further. 

Really appreciate the help, thanks for being so responsive!

All the best,
Emre

**Comment by ahus1** [comment]
As a followup I reviewed the documentation. 

The tutorial docs contain a description that was narrowed down to the example and therefore wrong. This is now fixed. I therefore close this issue.
